language: python

python:
  - "2.7"

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to install dependencies
install: "pip install -e .[postgresql,test]"

# command to run tests
script: "py.test --db=postgresql://postgres:@/travis_ci_test"
