language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to install dependencies
install: "pip install -e .[postgresql,test]"

# command to run tests
script: "py.test --db=postgresql://postgres:@/travis_ci_test"
