#
# Development environment services
# DO NOT USE FOR PRODUCTION
#

app:
  build: .
  command: gunicorn --paster develop.ini
  restart: always
  ports:
    - "3000:3000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./occams_forms:/app/occams_forms
    - ./develop.ini:/app/develop.ini
    - ./tests:/app/tests
    - occams_files:/files

postgres:
  image: postgres:9.5
  restart: always
  environment:
    - POSTGRES_USER=occams
    - POSTGRES_DB=occams
  ports:
    - "5432:5432"
  volumes:
    - occams_db:/var/lib/postgresql/data/

redis:
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
